### PR TITLE
Add Network Integration Action

### PR DESCRIPTION
**Pull request by roverflow**
# Summary

This PR adds the network integration workflow to the ansible-content-actions repo, this also adds some modifications to the workflow itself

## Changes
Adds an extra task that installs the required dependencies

### CODE REVIEW

**Review by KB-perByte — APPROVED** [review]
+1 from a workflow standpoint!

**Review by KB-perByte — DISMISSED** [review]
@roverflow address the CI failures, before you merge it.

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Please add some self-testing action, without it we have zero confidence that the content of this action would be usable.

**Review by ssbarnea — APPROVED** [review]
I made some changes to embed the self-test inside the ci workflow but other than this looks fine to me, approving.

**Pull request merged**
